### ISSUE TITLE
Month and year time shifts not working

### ISSUE THREAD

**Issue by szerwi** [AutohomeCorp/grafana-compare-queries#1]
I'm using Influxdb datasource.
When I try to select month or year time shift, there is an error "Data outside time range"
![image](https://user-images.githubusercontent.com/19311511/77228621-d87cc000-6b88-11ea-97af-1f8a52ab5a1e.png)

It works properly with time shift 366d
![image](https://user-images.githubusercontent.com/19311511/77228614-d0248500-6b88-11ea-9af3-9fa33524717a.png)

**Comment by nfw999** [comment]
Fix this bug in the latest version
