### ISSUE TITLE
ClickHouse datasource issue

### ISSUE THREAD

**Issue by juris** [AutohomeCorp/grafana-compare-queries#2]
When working with ClickHouse datasource. Only the last time shift executes.

Normal query without timeshift:
![Screenshot 2020-03-30 at 18 44 06](https://user-images.githubusercontent.com/1359141/77932683-8dfcf100-72b6-11ea-923a-086ea297db83.png)

Query with timeshift:
![Screenshot 2020-03-30 at 18 44 46](https://user-images.githubusercontent.com/1359141/77932751-a4a34800-72b6-11ea-8226-a02198207748.png)
Data on the graph is from query+7d, but the other data is missing.
I've checked what's happening with the requests, and for some reason, two queries have been cancelled.

If I copy queries as curl and execute them manually, I get a valid json response back.

**Comment by juris** [comment]
After some digging, we've figured out that this Grafana functional cancels requests:
```
async datasourceRequest(options: BackendSrvRequest): Promise<any> {
    // A requestId is provided by the datasource as a unique identifier for a
    // particular query. Every observable below has a takeUntil that subscribes to this.inFlightRequests and
    // will cancel/unsubscribe that observable when a new datasourceRequest with the same requestId is made
    if (options.requestId) {
      this.inFlightRequests.next(options.requestId);
    }
```

so I'm wondering, why it works fine with Influxdb datasource and fails with ClickHouse.

**Comment by nfw999** [comment]
Fix this bug in the latest version
