### ISSUE TITLE
use negative timeshift 

### ISSUE THREAD

**Issue by scelle** [AutohomeCorp/grafana-compare-queries#3]
Is it possible to use a negative value as a timeshift?

this is the case where I'm struggeling with:

[illustration](https://app.diagrams.net?lightbox=1&highlight=0000ff&nav=1&title=Untitled%20Diagram%20(1).drawio#R7Ztbc6IwFIB%2FjY%2Fd4Sbio7q23ZntTLs%2BdPoYIUJmgTAh3vbXb5Agl1C1gohUX5RDOEnOl3OSnGBPnXibJwIC5wVb0O0pkrXpqT97CvtoQ%2FYVSbaxZKD1Y4FNkBWL5FQwQ%2F8gF0pcukQWDHMFKcYuRUFeaGLfhybNyQAheJ0vtsBuvtYA2FAQzEzgitJ3ZFEnlhrKIJU%2FQ2Q7Sc2yzjvsgaQw70noAAuvMyJ12lMnBGMa%2F%2FI2E%2BhGxkvsEj%2F3%2BMndfcMI9OkpD0yC0cfLagHfXrfT5%2B2v0ab%2F%2BP6gxFpWwF3yDlPkQd5guk2sAH1rFBmTXZkuCENk9tSxQz2XCWT2U2wLbx60cublLXuC2IOUbFmBdWrUPjeUk7FnIiPQBRSt8lAAZ2vv1e1reMWItUSR%2BDjUuJptQknKawjxkpiQP5S1YUGPPjyiiAJiQyooYj8yvU5FO0RfwDUUcPkMygFaPvaZcGyB0IEWh1ULN26QB%2BmHrupa%2FFAzLHW9LpgFReppLFM9SUG8WITwIrzl7%2Bmf%2B%2Buq%2FikourB%2FyqrA6wTvzIBaINedYBeTXVl1YZjQjFiGlOC%2FMHNnbvQ1Zvz2o%2B0bNbEVFEkNsx1UZNt2UrpSlxcWFTVNyhBIwa6zKpr4ZrzqvqQRVyJ7vVWXNPKghWsa7T5HFrAZck2RV1DUtDf3BbZT%2BU63K7Fav3tuV1e32vfcaar6uTPt8IiiS%2FOqutNsOyijJlBFPUrDnKqudtrOSZVrAiUoappU9bXLzbEqmvhWnKrqQqTtoLoS%2FLqeMpOVmkAJipom1f2U2VET34pT3TNmJWd3Z6%2Fji6k34zSaTWbMEpsdCqM2wcvgU5IrSCjc5ET8hQkwTzRIvUOMi%2FvTJLGYwa2V4C5uh7Nkc2b6qk3qXwEcNP21Y9i23JxHR3lDMan%2Beb7VNMpzCeemfho%2Bo77ETH9LtNrmO31ZANJ4dD8e3PdvxzQS3etPbh00%2FbVHaMuje%2F0prFbT2BRGfMXwfup7ZbXFE4FW9TTWTfG6ovusZ38wxPYHnpCB%2FHvovz0N3Acxvs9YjVEDQkSXrMvYF%2FiweE7zUPJnZBxa9kCNi4CLbJ9dmgweZPJxNDsgE7gjfsNDlhVVM147iMJZAMyozjUBAZOxeca3dpvE9PStZHoRJqHP94ZKuRdlxoRslAyK4qb6nKmllIYi0Agw4xCNO0WKj7yk0EGLiE8ERirxns7QKeSD9ySuRqds4teBF3Xen4e7L2iDQ7TEuamrtJTh5Wixy%2FSfCXEgTP%2FfoU7%2FAw%3D%3D)
2 series of testresults (e1,e2) that I want to overlay.  these series have different lengths.
I want to combine the compare queries plugin functionality with the built-in timeshift function to show both series overlapped
if e2 series is much shorter and close to "now" (current time), then I have a problem.  
If I add a timeshift to e1, the results will go past the current time and I am not able to shift the whole graphic in a negative direction, because the built-in timeshift function does not allow negative direction neither.

**Comment by nfw999** [comment]
I failed to open the illustration link. I think the time shift is relative. You can adjust the time shift to positive by selecting the appropriate basic query.

**Comment by scelle** [comment]
[new try](https://app.diagrams.net?lightbox=1&highlight=0000ff&nav=1&title=Untitled%20Diagram%20(1).drawio#R7Ztbc6IwFIB%2FjY%2Fd4Sbio7q23ZntTLs%2BdPoYIUJmgTAh3vbXb5Agl1C1gohUX5RDOEnOl3OSnGBPnXibJwIC5wVb0O0pkrXpqT97CvtoQ%2FYVSbaxZKD1Y4FNkBWL5FQwQ%2F8gF0pcukQWDHMFKcYuRUFeaGLfhybNyQAheJ0vtsBuvtYA2FAQzEzgitJ3ZFEnlhrKIJU%2FQ2Q7Sc2yzjvsgaQw70noAAuvMyJ12lMnBGMa%2F%2FI2E%2BhGxkvsEj%2F3%2BMndfcMI9OkpD0yC0cfLagHfXrfT5%2B2v0ab%2F%2BP6gxFpWwF3yDlPkQd5guk2sAH1rFBmTXZkuCENk9tSxQz2XCWT2U2wLbx60cublLXuC2IOUbFmBdWrUPjeUk7FnIiPQBRSt8lAAZ2vv1e1reMWItUSR%2BDjUuJptQknKawjxkpiQP5S1YUGPPjyiiAJiQyooYj8yvU5FO0RfwDUUcPkMygFaPvaZcGyB0IEWh1ULN26QB%2BmHrupa%2FFAzLHW9LpgFReppLFM9SUG8WITwIrzl7%2Bmf%2B%2Buq%2FikourB%2FyqrA6wTvzIBaINedYBeTXVl1YZjQjFiGlOC%2FMHNnbvQ1Zvz2o%2B0bNbEVFEkNsx1UZNt2UrpSlxcWFTVNyhBIwa6zKpr4ZrzqvqQRVyJ7vVWXNPKghWsa7T5HFrAZck2RV1DUtDf3BbZT%2BU63K7Fav3tuV1e32vfcaar6uTPt8IiiS%2FOqutNsOyijJlBFPUrDnKqudtrOSZVrAiUoappU9bXLzbEqmvhWnKrqQqTtoLoS%2FLqeMpOVmkAJipom1f2U2VET34pT3TNmJWd3Z6%2Fji6k34zSaTWbMEpsdCqM2wcvgU5IrSCjc5ET8hQkwTzRIvUOMi%2FvTJLGYwa2V4C5uh7Nkc2b6qk3qXwEcNP21Y9i23JxHR3lDMan%2Beb7VNMpzCeemfho%2Bo77ETH9LtNrmO31ZANJ4dD8e3PdvxzQS3etPbh00%2FbVHaMuje%2F0prFbT2BRGfMXwfup7ZbXFE4FW9TTWTfG6ovusZ38wxPYHnpCB%2FHvovz0N3Acxvs9YjVEDQkSXrMvYF%2FiweE7zUPJnZBxa9kCNi4CLbJ9dmgweZPJxNDsgE7gjfsNDlhVVM147iMJZAMyozjUBAZOxeca3dpvE9PStZHoRJqHP94ZKuRdlxoRslAyK4qb6nKmllIYi0Agw4xCNO0WKj7yk0EGLiE8ERirxns7QKeSD9ySuRqds4teBF3Xen4e7L2iDQ7TEuamrtJTh5Wixy%2FSfCXEgTP%2FfoU7%2FAw%3D%3D)
I'm not sure if I understand what you mean by 

> selecting the appropriate basic query

I'm using influxdb (1.x version) and this query language doesn't support any time shifting as far as I know.  (from flux 2.0 on this should be possible though) 

I also forgot to mention that in my case my application is dynamic.  Users can compare different measuring results by selecting  event id.  On selection, the timeshift is calculated and written to a template variable that is used in the timeshift field.

Anyhow, I'm working on a workaround now.  Upon calculating the required time shift, I will also calculate the required custom time range (from now - xx, to now + yy) and update this one.  

Pascal

**Comment by nfw999** [comment]
Just As 【positive time shift on E1】, calculate the time range of series e1  (from now - xx, to now + yy) and use e1 as the base query.

**Comment by scelle** [comment]
ok, thanks.
