### ISSUE TITLE
Not working at Grafana V6.7.2

### ISSUE THREAD

**Issue by fadjar340** [AutohomeCorp/grafana-compare-queries#4]
Hi,

This datasource not working at Grafana 6.7.2 with elasticsearch backend
[edited]
![image](https://user-images.githubusercontent.com/1247073/78465868-249d3800-7725-11ea-9841-55b7d9b365c2.png)

Just tried out but no luck

Regards,
Fadjar340

**Comment by nfw999** [comment]
The value of the query option is the refid of the basic query

In your case, the value of the query should be filled in "A"

![image](https://user-images.githubusercontent.com/33611490/78969358-5a815880-7b39-11ea-94a8-5bc2dcb4523f.png)

**Comment by fadjar340** [comment]
Still no luck.....

![image](https://user-images.githubusercontent.com/1247073/78970860-80582e80-7b34-11ea-90ad-1c57045e88b6.png)

**Comment by nfw999** [comment]
DataSources select CompareQueries 

![image](https://user-images.githubusercontent.com/33611490/78971183-961e2180-7b3d-11ea-8afb-906ae2eafd4a.png)

**Comment by fadjar340** [comment]
Already:
![image](https://user-images.githubusercontent.com/1247073/78971532-0032c880-7b36-11ea-9e9a-7b629c8d8663.png)

And the result:
![image](https://user-images.githubusercontent.com/1247073/78971588-1b053d00-7b36-11ea-8221-3f90c2afcef1.png)

**Comment by fadjar340** [comment]
YESSSS......

Working as expected...
The problem is in the step of the datasource selection..

BTW, thank you for the execelent panel....


Regards,
Fadjar Tandabawana
